name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jayantvashisth/assignment1 --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} .

      - name: Push image to Docker Hub
        run: docker push jayantvashisth/assignment1:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]

    steps:
      - name: Pull image from Docker Hub
        run: docker pull jayantvashisth/assignment1:latest

      - name: Delete old container (if exists)
        run: docker rm -f assignment1-container

      - name: Run Docker container
        run: docker run -d -p 5000:5000 -e MONGODB_URI=${{secrets.MONGODB_URI}} --name assignment1-container jayantvashisth/assignment1
